from pymongo import MongoClient

# 1. Connect
client = MongoClient("mongodb://localhost:27017/")
db = client["finance_db"]          # Create/Use database
collection = db["transactions"]    # Create/Use collection

# 2. CREATE (Insert) - Insert a dictionary
doc = {"amount": 50, "category": "Food", "type": "expense", "date": "2026-06-09"}
result = collection.insert_one(doc)
print(result.inserted_id)  # Unique ID generated by MongoDB

# 3. READ (Find)
all_docs = collection.find({})  # Empty {} means "get all"
for doc in all_docs:
    print(doc)

# Find specific: expenses under $20
cheap_expenses = collection.find({"type": "expense", "amount": {"$lt": 20}})

# 4. UPDATE - Use $set to change fields
collection.update_one({"_id": result.inserted_id}, {"$set": {"amount": 75}})

# 5. DELETE
collection.delete_one({"_id": result.inserted_id})

pipeline = [
    # Stage 1: Filter only expenses
    {"$match": {"type": "expense"}},
    # Stage 2: Group by category and sum the amounts
    {"$group": {"_id": "$category", "total_spent": {"$sum": "$amount"}}},
    # Stage 3: Sort highest spenders first
    {"$sort": {"total_spent": -1}}
]
results = collection.aggregate(pipeline)
for item in results:
    print(f"Category: {item['_id']}, Total: ${item['total_spent']}")